package com.gestioncitas_trabajofinal.view;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import com.gestioncitas_trabajofinal.controller.RegisterController;
import java.util.Date;
import javax.swing.JOptionPane;
import com.toedter.calendar.*;

/**
 * Ventana para el registro de nuevos pacientes en el sistema.
 * Contiene un formulario para capturar los datos personales del usuario.
 * @author lumic    
 */
public class Register extends javax.swing.JFrame {
    
    private final RegisterController controller;
    
    /**
     * Constructor que inicializa los componentes de la ventana y el controlador.
     */
    public Register() {
        initComponents();
        this.controller = new RegisterController();
        // Evita que el usuario pueda escribir directamente en el campo de fecha.
        calendario.getDateEditor().setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Issael
    private void initComponents() {
        jPanel1 = new JPanel();
        logo = new JLabel();
        logoName = new JLabel();
        favicon = new JLabel();
        title = new JLabel();
        nombreLabel = new JLabel();
        nombreTXT = new JTextField();
        div1 = new JSeparator();
        apellidosLabel = new JLabel();
        apellidosTXT = new JTextField();
        div3 = new JSeparator();
        dniLabel = new JLabel();
        dniTxt = new JTextField();
        div4 = new JSeparator();
        fechaLabel = new JLabel();
        div5 = new JSeparator();
        correoLabel = new JLabel();
        correoTxt = new JTextField();
        div6 = new JSeparator();
        telfLabel = new JLabel();
        telefonoTxt = new JTextField();
        div7 = new JSeparator();
        contraseñaLabel = new JLabel();
        contrasenaTXT = new JPasswordField();
        div2 = new JSeparator();
        registrarseBtn = new JButton();
        cancelarBTN = new JButton();
        background = new JLabel();
        correoLabel1 = new JLabel();
        direccionTXT = new JTextField();
        div8 = new JSeparator();
        calendario = new JDateChooser();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBackground(Color.white);
            jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .
            EmptyBorder ( 0, 0 ,0 , 0) ,  "JFor\u006dDesi\u0067ner \u0045valu\u0061tion" , javax. swing .border . TitledBorder. CENTER ,javax . swing
            . border .TitledBorder . BOTTOM, new java. awt .Font ( "Dia\u006cog", java .awt . Font. BOLD ,12 ) ,
            java . awt. Color .red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener( new java. beans .PropertyChangeListener ( )
            { @Override public void propertyChange (java . beans. PropertyChangeEvent e) { if( "bord\u0065r" .equals ( e. getPropertyName () ) )
            throw new RuntimeException( ) ;} } );
            jPanel1.setLayout(null);

            //---- logo ----
            logo.setHorizontalAlignment(SwingConstants.CENTER);
            logo.setIcon(new ImageIcon(getClass().getResource("/View/imagenes/logo.png")));
            jPanel1.add(logo);
            logo.setBounds(0, 110, 280, 150);

            //---- logoName ----
            logoName.setFont(new Font("Tahoma", Font.BOLD, 18));
            logoName.setForeground(Color.white);
            logoName.setHorizontalAlignment(SwingConstants.CENTER);
            logoName.setText("CitaSmart");
            jPanel1.add(logoName);
            logoName.setBounds(0, 250, 280, logoName.getPreferredSize().height);

            //---- favicon ----
            favicon.setFont(new Font("Tahoma", Font.BOLD, 18));
            favicon.setForeground(Color.black);
            favicon.setIcon(new ImageIcon(getClass().getResource("/View/imagenes/favicon.png")));
            favicon.setText("CitaSmart");
            jPanel1.add(favicon);
            favicon.setBounds(310, 30, 130, favicon.getPreferredSize().height);

            //---- title ----
            title.setFont(new Font("Tahoma", Font.BOLD, 20));
            title.setForeground(Color.black);
            title.setHorizontalAlignment(SwingConstants.CENTER);
            title.setText("REGISTRARSE");
            jPanel1.add(title);
            title.setBounds(280, 90, 470, title.getPreferredSize().height);

            //---- nombreLabel ----
            nombreLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            nombreLabel.setForeground(Color.black);
            nombreLabel.setText("NOMBRES");
            jPanel1.add(nombreLabel);
            nombreLabel.setBounds(310, 140, 190, nombreLabel.getPreferredSize().height);

            //---- nombreTXT ----
            nombreTXT.setBackground(Color.white);
            nombreTXT.setFont(new Font("Tahoma", Font.PLAIN, 12));
            nombreTXT.setBorder(null);
            nombreTXT.addActionListener(e -> nombreTXTActionPerformed(e));
            jPanel1.add(nombreTXT);
            nombreTXT.setBounds(310, 160, 190, 30);
            jPanel1.add(div1);
            div1.setBounds(310, 190, 190, div1.getPreferredSize().height);

            //---- apellidosLabel ----
            apellidosLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            apellidosLabel.setForeground(Color.black);
            apellidosLabel.setText("APELLIDOS");
            jPanel1.add(apellidosLabel);
            apellidosLabel.setBounds(530, 140, 190, apellidosLabel.getPreferredSize().height);

            //---- apellidosTXT ----
            apellidosTXT.setBackground(Color.white);
            apellidosTXT.setFont(new Font("Tahoma", Font.PLAIN, 12));
            apellidosTXT.setBorder(null);
            apellidosTXT.addActionListener(e -> apellidosTXTActionPerformed(e));
            jPanel1.add(apellidosTXT);
            apellidosTXT.setBounds(530, 160, 190, 30);
            jPanel1.add(div3);
            div3.setBounds(530, 190, 190, div3.getPreferredSize().height);

            //---- dniLabel ----
            dniLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            dniLabel.setForeground(Color.black);
            dniLabel.setText("DNI");
            jPanel1.add(dniLabel);
            dniLabel.setBounds(310, 220, 190, dniLabel.getPreferredSize().height);

            //---- dniTxt ----
            dniTxt.setBackground(Color.white);
            dniTxt.setFont(new Font("Tahoma", Font.PLAIN, 12));
            dniTxt.setBorder(null);
            dniTxt.addActionListener(e -> dniTxtActionPerformed(e));
            jPanel1.add(dniTxt);
            dniTxt.setBounds(310, 240, 190, 30);
            jPanel1.add(div4);
            div4.setBounds(310, 270, 190, div4.getPreferredSize().height);

            //---- fechaLabel ----
            fechaLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            fechaLabel.setForeground(Color.black);
            fechaLabel.setText("FECHA DE NACIMIENTO");
            jPanel1.add(fechaLabel);
            fechaLabel.setBounds(530, 220, 190, fechaLabel.getPreferredSize().height);
            jPanel1.add(div5);
            div5.setBounds(530, 270, 190, div5.getPreferredSize().height);

            //---- correoLabel ----
            correoLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            correoLabel.setForeground(Color.black);
            correoLabel.setText("CORREO ELECTRONICO");
            jPanel1.add(correoLabel);
            correoLabel.setBounds(310, 300, 190, correoLabel.getPreferredSize().height);

            //---- correoTxt ----
            correoTxt.setBackground(Color.white);
            correoTxt.setFont(new Font("Tahoma", Font.PLAIN, 12));
            correoTxt.setBorder(null);
            correoTxt.addActionListener(e -> correoTxtActionPerformed(e));
            jPanel1.add(correoTxt);
            correoTxt.setBounds(310, 320, 190, 30);
            jPanel1.add(div6);
            div6.setBounds(310, 350, 190, 10);

            //---- telfLabel ----
            telfLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            telfLabel.setForeground(Color.black);
            telfLabel.setText("TELEFONO");
            jPanel1.add(telfLabel);
            telfLabel.setBounds(310, 380, 190, telfLabel.getPreferredSize().height);

            //---- telefonoTxt ----
            telefonoTxt.setBackground(Color.white);
            telefonoTxt.setFont(new Font("Tahoma", Font.PLAIN, 12));
            telefonoTxt.setBorder(null);
            telefonoTxt.addActionListener(e -> telefonoTxtActionPerformed(e));
            jPanel1.add(telefonoTxt);
            telefonoTxt.setBounds(310, 400, 190, 30);
            jPanel1.add(div7);
            div7.setBounds(310, 430, 190, div7.getPreferredSize().height);

            //---- contraseñaLabel ----
            contraseñaLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            contraseñaLabel.setForeground(Color.black);
            contraseñaLabel.setText("CONTRASE\u00d1A");
            jPanel1.add(contraseñaLabel);
            contraseñaLabel.setBounds(530, 380, 190, contraseñaLabel.getPreferredSize().height);

            //---- contrasenaTXT ----
            contrasenaTXT.setBackground(Color.white);
            contrasenaTXT.setFont(new Font("Tahoma", Font.PLAIN, 12));
            contrasenaTXT.setBorder(null);
            jPanel1.add(contrasenaTXT);
            contrasenaTXT.setBounds(530, 400, 190, 30);
            jPanel1.add(div2);
            div2.setBounds(530, 430, 190, div2.getPreferredSize().height);

            //---- registrarseBtn ----
            registrarseBtn.setBackground(new Color(0x006699));
            registrarseBtn.setFont(new Font("Tahoma", Font.BOLD, 12));
            registrarseBtn.setForeground(Color.white);
            registrarseBtn.setText("REGISTRARSE");
            registrarseBtn.addActionListener(e -> registrarseBtnActionPerformed(e));
            jPanel1.add(registrarseBtn);
            registrarseBtn.setBounds(380, 470, 120, 40);

            //---- cancelarBTN ----
            cancelarBTN.setBackground(new Color(0xcc0000));
            cancelarBTN.setFont(new Font("Tahoma", Font.BOLD, 12));
            cancelarBTN.setForeground(Color.white);
            cancelarBTN.setText("CANCELAR");
            cancelarBTN.addActionListener(e -> cancelarBTNActionPerformed(e));
            jPanel1.add(cancelarBTN);
            cancelarBTN.setBounds(530, 470, 120, 40);

            //---- background ----
            background.setIcon(new ImageIcon(getClass().getResource("/View/imagenes/background2.jpg")));
            jPanel1.add(background);
            background.setBounds(0, 0, 280, 570);

            //---- correoLabel1 ----
            correoLabel1.setFont(new Font("Tahoma", Font.PLAIN, 14));
            correoLabel1.setForeground(Color.black);
            correoLabel1.setText("DIRECCION");
            jPanel1.add(correoLabel1);
            correoLabel1.setBounds(530, 300, 190, correoLabel1.getPreferredSize().height);

            //---- direccionTXT ----
            direccionTXT.setBackground(Color.white);
            direccionTXT.setFont(new Font("Tahoma", Font.PLAIN, 12));
            direccionTXT.setBorder(null);
            direccionTXT.addActionListener(e -> direccionTXTActionPerformed(e));
            jPanel1.add(direccionTXT);
            direccionTXT.setBounds(530, 320, 190, 30);
            jPanel1.add(div8);
            div8.setBounds(530, 350, 190, 10);

            //---- calendario ----
            calendario.setBackground(new Color(0xdddddd));
            calendario.setForeground(Color.white);
            calendario.setAutoscrolls(true);
            jPanel1.add(calendario);
            calendario.setBounds(530, 242, 190, 30);

            {
                // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < jPanel1.getComponentCount(); i++) {
                    Rectangle bounds = jPanel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = jPanel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                jPanel1.setMinimumSize(preferredSize);
                jPanel1.setPreferredSize(preferredSize);
            }
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void direccionTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTXTActionPerformed
   
    /**
     * Maneja el clic en el botón 'Cancelar'. Cierra la ventana de registro y vuelve a la de Login.
     * @param evt El evento de acción.
     */
    private void cancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTNActionPerformed
        // Abrir la ventana de login y cerrar la actual (registro)
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBTNActionPerformed
    
    /**
     * Maneja el clic en el botón 'Registrarse'. Inicia el proceso de validación y registro.
     * @param evt El evento de acción.
     */
    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        validarYRegistrar();
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void telefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtActionPerformed

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void apellidosTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTXTActionPerformed

    private void nombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTXTActionPerformed

    // ------------------- MÉTODOS PRIVADOS DE AYUDA -------------------

    /**
     * Orquesta el proceso de registro: valida los campos y, si son correctos,
     * llama al controlador para registrar al paciente.
     */
    private void validarYRegistrar() {
        String nombres = nombreTXT.getText().trim();
        String apellidos = apellidosTXT.getText().trim();
        String dni = dniTxt.getText().trim();
        String correo = correoTxt.getText().trim();
        String telefono = telefonoTxt.getText().trim();
        String direccion = direccionTXT.getText().trim();
        String password = new String(contrasenaTXT.getPassword()).trim();
        Date fechaNacimiento = calendario.getDate();

        // Si la validación de los campos es exitosa, procede con el registro.
        if (validarCampos(nombres, apellidos, dni, correo, telefono, direccion, password, fechaNacimiento)) {
            boolean registrado = controller.registrarPaciente(correo, password, nombres, apellidos, telefono, dni, fechaNacimiento, direccion);
            
            // Si el registro en la base de datos fue exitoso, vuelve al Login.
            if (registrado) {
                new Login().setVisible(true);
                this.dispose();
            }
        }
    }

    /**
     * Valida todos los campos del formulario de registro.
     * Muestra un único mensaje de error si encuentra alguna inconsistencia.
     * @return {@code true} si todos los campos son válidos, {@code false} en caso contrario.
     */
    private boolean validarCampos(String nombres, String apellidos, String dni, String correo, String telefono, String direccion, String password, Date fechaNacimiento) {
        if (nombres.isEmpty() || apellidos.isEmpty() || dni.isEmpty() || correo.isEmpty() || telefono.isEmpty() || direccion.isEmpty() || password.isEmpty() || fechaNacimiento == null) {
            mostrarError("Todos los campos son obligatorios.");
            return false;
        }
        if (!nombres.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            mostrarError("El nombre solo puede contener letras y espacios.");
            return false;
        }
        if (!apellidos.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            mostrarError("El apellido solo puede contener letras y espacios.");
            return false;
        }
        if (!dni.matches("\\d{8}")) {
            mostrarError("El DNI debe contener exactamente 8 números.");
            return false;
        }
        if (!telefono.matches("\\d{7,9}")) {
            mostrarError("El teléfono debe contener entre 7 y 9 números.");
            return false;
        }
        if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")) {
            mostrarError("El formato del correo electrónico no es válido.");
            return false;
        }
        if (password.length() < 6) {
            mostrarError("La contraseña debe tener al menos 6 caracteres.");
            return false;
        }
        return true;
    }

    /**
     * Muestra una ventana de diálogo con un mensaje de error.
     * @param mensaje El mensaje de error a mostrar.
     */
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error de validación", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Issael
    private JPanel jPanel1;
    private JLabel logo;
    private JLabel logoName;
    private JLabel favicon;
    private JLabel title;
    private JLabel nombreLabel;
    private JTextField nombreTXT;
    private JSeparator div1;
    private JLabel apellidosLabel;
    private JTextField apellidosTXT;
    private JSeparator div3;
    private JLabel dniLabel;
    private JTextField dniTxt;
    private JSeparator div4;
    private JLabel fechaLabel;
    private JSeparator div5;
    private JLabel correoLabel;
    private JTextField correoTxt;
    private JSeparator div6;
    private JLabel telfLabel;
    private JTextField telefonoTxt;
    private JSeparator div7;
    private JLabel contraseñaLabel;
    private JPasswordField contrasenaTXT;
    private JSeparator div2;
    private JButton registrarseBtn;
    private JButton cancelarBTN;
    private JLabel background;
    private JLabel correoLabel1;
    private JTextField direccionTXT;
    private JSeparator div8;
    private JDateChooser calendario;
    // End of variables declaration//GEN-END:variables
}
